name: 📡 WhalePulse Telegram Notifier

on:
  push:
    branches:
      - master  # اجرای خودکار هنگام push به شاخه master
  workflow_dispatch:  # امکان اجرای دستی از تب Actions

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout repository
        uses: actions/checkout@v4

      - name: 📤 Send Telegram notification
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          COMMIT_AUTHOR="${{ github.event.head_commit.author.name }}"
          COMMIT_TIME=$(date '+%Y-%m-%d %H:%M:%S')
          MESSAGE="✅ WhalePulse-Pro updated!\n👤 By: ${COMMIT_AUTHOR}\n📝 Message: ${COMMIT_MESSAGE}\n⏰ Time: ${COMMIT_TIME}"
          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
            -d chat_id=${CHAT_ID} \
            -d text="${MESSAGE}"
