name: Notify Telegram on Push

on:
  push:
    branches:
      - master  # چون شاخه‌ی فعلی master هست

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          MESSAGE="✅ WhalePulse-Pro updated! New push to master branch."
          curl -s -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendMessage \
            -d chat_id=${CHAT_ID} \
            -d text="${MESSAGE}"
